.extern linkedlist_create
.type linkedlist_create, @function

.extern linkedlist_free
.type linkedlist_free, @function

.extern linkedlist_push
.type linkedlist_push, @function

.extern linkedlist_get
.type linkedlist_get, @function

.extern linkedlist_find
.type linkedlist_find, @function

.extern linkedlist_insert
.type linkedlist_insert, @function

.extern linkedlist_remove
.type linkedlist_remove, @function

.extern linkedlist_removeValue
.type linkedlist_removeValue, @function
